name: Facilikoen II
favicon: null
layout_spectrum: 0.577134951017797
typography_spectrum: 0.8763652869965881
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8941028614062816
  lightness: 0.6611666691023856
  saturation: 0.020817735698074102
  rhythmicContrast: 0.44008127972483635
purpose: []
