name: Facilikoen II
favicon: null
layout_spectrum: 0.25529
typography_spectrum: 0.8763652869965881
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4e4945'
    - '#dbd0ac'
    - '#8e806a'
    - '#fffaf0'
    - '#e3de00'
  brandStrength: 0.8941028614062816
  lightness: 0.6611666691023856
  saturation: 0.020817735698074102
  rhythmicContrast: 0.44008127972483635
purpose: []
