name: Facilikoen II
favicon: null
layout_spectrum: 0
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f6f4'
    - '#deddd9'
    - '#c2beb6'
    - '#a09789'
    - '#8c8071'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
